package env

const (
	LSDSWait                = "LSDSWait"
	RemoteCallPolicy        = "remoteCallpolicy"
	Local                   = "local"
	Port                    = "port"
	WorkflowRuntimeFilePath = "workflowRuntimeFilePath"
	WorkflowPath            = "workflowPath"
	FuntionsPath            = "functionPath"
	WorkflowName            = "workflowName"
	SelfName                = "selfName"
	Environment             = "Environment"
	RedisIp                 = "RedisIp"
	RedisPort               = "RedisPort"
	RedisPassword           = "RedisPassword"
	DefaultDb               = "DefaultDb"
	TassFileRoot            = "/tass/"
	Mock                    = "Mock"
	StaticMiddleware        = "StaticMiddleware"
	QPSMiddleware           = "QPSMiddleware"
	InstanceScorePolicy     = "InstanceScorePolicy"
	CreatePolicy            = "CreatePolicy"
	TTL                     = "TTL"
	TraceAgentHostPort      = "TraceAgentHostPort"
)
